### ISSUE TITLE
so i inject to BFV client and don't worked.

### ISSUE THREAD

**Issue by Garfield-Chen** [Speedi13/BFV-Decryption#1]
in ObfuscationMgr  and GetLocalPlayer function:

-> if (iterator.mpNode == table->mpBucketArray[table->mnBucketCount]) 

here return null !!

**Comment by Speedi13** [comment]
yes that should happen if it doesn't find the entry inside the hash map / table.
Have you tried injecting while being in singleplayer and multiplayer?
On another note have you been using the latest offsets?
https://github.com/Speedi13/BFV-Decryption/blob/master/BfvDecryptionDemo/FrostbiteSDK.h#L4

**Comment by Speedi13** [comment]
this problem is fixed using the correct ClientGameContext offsets
https://github.com/Speedi13/BFV-Decryption/blob/master/BfvDecryptionDemo/FrostbiteSDK.h#L4
