### ISSUE TITLE
Access violation reading location 0x0000000140001000

### ISSUE THREAD

**Issue by albert-92** [Speedi13/BFV-Decryption#2]
Hi,

i build your dll and tried to load it from my application.

However it always crashes when it tries to read the 
https://github.com/Speedi13/BFV-Decryption/blob/0e2d1d1799822b4fd592623cae7b100b4ad68308/BfvDecryptionDemo/DllMain.cpp#L35
in the `DataCompare` function.
https://github.com/Speedi13/BFV-Decryption/blob/0e2d1d1799822b4fd592623cae7b100b4ad68308/BfvDecryptionDemo/DllMain.cpp#L116

I get the error `Access violation reading location 0x0000000140001000` in Visual Studio.

Any suggestion how i can fix this?

Thanks

**Comment by coman3** [comment]
This is designed to be injected using a dll injector like `xenos` i think :)

**Comment by Speedi13** [comment]
@coman3 is correct. This DLL needs to be running into the game. We use a method called DLL injection for that.
I posted a simple dll injector for another project:
https://github.com/Speedi13/DriveSizeSpoofer/blob/master/DriveSizeManager/Injector.cpp
Tho this can be re-written using ReadProcessMemory if you want to stay external.

**Comment by albert-92** [comment]
Thanks
