### ISSUE TITLE
Can you tell me how to find OFFSET_OBFUSCATIONMGR?

### ISSUE THREAD

**Issue by byshiyi** [Speedi13/BFV-Decryption#3]
Can you tell me how to find OFFSET_OBFUSCATIONMGR? In the madness, there is no clue! I tried to check all the BF1 and BFV posts, maybe it was the reason I came late, I feel that I missed everything about finding information! This makes me want to crash.

**Comment by RmznTURAN** [comment]
ben Bf5 güncelle geldinde sonra calismiyor BFV_Trainer_v1.3  lüften yardim edin ve güncelle v1.4!

**Comment by Speedi13** [comment]
now this has to be done with this function anyway ;)
https://www.unknowncheats.me/forum/2504594-post354.html

**Comment by RmznTURAN** [comment]
we really don't know how to do this and thank you!

Speedi13 <notifications@github.com>, 26 Haz 2019 Çar, 23:29 tarihinde şunu
yazdı:
